### ISSUE TITLE
finish method signature

### ISSUE THREAD

**Issue by daa84** [mvdnes/zip-rs#10]
https://github.com/mvdnes/zip-rs/blob/master/src/write.rs#L188
does method:
pub fn finish(mut self) -> ZipResult<W>

must be
pub fn finish(&mut self) -> ZipResult<W>

why not pass here a reference?

**Comment by mvdnes** [comment]
Although this was done on purpose, I cannot see any reason for it.
I will update it to match your proposed signature, as it should not break things as far as I can see.  :+1:

**Comment by daa84** [comment]
Thanks
