### ISSUE TITLE
Can't compile to WASM.

### ISSUE THREAD

**Issue by KoStard** [mvdnes/zip-rs#113]
When I add `zip = "0.5.3"` to my Cargo.toml and run `cargo web build` I get this error:
```
error: failed to run custom build command for `bzip2-sys v0.1.7`

--- stdout
TARGET = Some("wasm32-unknown-unknown")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "bzip2-1.0.6" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-o" "/.../target/wasm32-unknown-unknown/debug/build/bzip2-sys-6721f856d29ce7e6/out/lib/bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c"
cargo:warning=In file included from bzip2-1.0.6/blocksort.c:22:
cargo:warning=bzip2-1.0.6/bzlib_private.h:25:10: fatal error: 'stdlib.h' file not found
cargo:warning=#include <stdlib.h>
cargo:warning=         ^~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr


error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "bzip2-1.0.6" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-o" "/.../target/wasm32-unknown-unknown/debug/build/bzip2-sys-6721f856d29ce7e6/out/lib/bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c" with args "clang" did not execute successfully (status code exit code: 1).
```
Any suggestions?

**Comment by KoStard** [comment]
If I understand the problem here is associated with cdylib... When I remove it and try to compile with emscripten I don't get this error, but I miss some stdweb features like js_export... But why I get this problem at all?

**Comment by mvdnes** [comment]
I have no experience with using WASM, however if you don't use bzip2 compression, you can disable this feature. The normal deflate compression should be sufficient.

**Comment by OrangeTux** [comment]
Putting this in your `Cargo.toml` worked for me:

``` toml
[dependencies.zip]
default-features = false
zip = "0.5.0"
```

**Comment by ibaryshnikov** [comment]
There's a `deflate` feature in `Cargo.toml` of `zip-rs`
```toml
[features]
deflate = ["flate2/rust_backend"]
```
Extending the previous comment, it compiles and able to decompress files with
```toml
[dependencies.zip]
version = "0.5.4"
default-features = false
features = ["deflate"]
```
Tested it with `wasm-pack build`, but it should also work with `cargo-web`

**Comment by tonyhb** [comment]
Quick heads up even if you move this to wasm:  crc32 checking is going to really, really slow you down (cpu 100%, ~3s for a 212kb json file):

<img width="938" alt="Screen Shot 2020-06-14 at 10 25 32 PM" src="https://user-images.githubusercontent.com/306177/84620894-32023b80-aea7-11ea-90f1-301a067d449d.png">

I wonder if there's a faster approach to CRC32 checking - or if you can bypass the validation at all.

**Comment by rylev** [comment]
@KoStard As far as I understand this issue is resolved. Perhaps we can change the title of the issue to "Document how to use with Wasm"?

**Comment by KoStard** [comment]
Yes, it's working, so will close the issue, but yeah we definitely will need information about how to use with WASM :)

**Comment by sunnywanggit** [comment]
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

**Comment by sunnywanggit** [comment]
The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://192.168.30.100:3300' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.
