### ISSUE TITLE
date tm_mon validation failure

### ISSUE THREAD

**Issue by ArtemGr** [mvdnes/zip-rs#128]
zip fails to validate a zero `tm_mon` produced by the filesystem, e.g.

    let meta = unwrap! (file.metadata());
    if !meta.is_file() {continue}
    let modified = unwrap! (unwrap! (meta.modified()) .duration_since (std::time::UNIX_EPOCH));
    let modified = time::Timespec::new (modified.as_secs() as i64, modified.subsec_nanos() as i32);
    let modified = time::at_utc (modified);
    let lm = unwrap! (zip::DateTime::from_time (modified));

Line

https://github.com/mvdnes/zip-rs/blob/003440bfe3823a01f11047c42e441999f0554daf/src/types.rs#L114

looks like a copy-paste error to me.

**Comment by mvdnes** [comment]
Thanks :+1:
