### ISSUE TITLE
Release same version as in the docs: file_names method missing

### ISSUE THREAD

**Issue by cortopy** [mvdnes/zip-rs#133]
I was looking at the docs and wanted to use the `file_names` method of a ZipArchive and was getting caught by compile errors. I then saw this method is quite new and added in a recent [commit](https://github.com/mvdnes/zip-rs/commit/91c93579f27d2455cefaf90365528df56c764109)

Has it been published?

**Comment by mvdnes** [comment]
I just published a new versin containing the commits you mentioned.
