### ISSUE TITLE
Problem with reading ZIP file - "Compression method not supported"

### ISSUE THREAD

**Issue by fschutt** [mvdnes/zip-rs#134]
I have this ZIP file containing heightmap data, but for some reason unzipping it using zip-rs returns:

> "Error while reading zip file "N48E008.SRTMGL3.hgt.zip": Unsupported Zip archive: Compression method not supported"

I don't know too much about ZIP compression - it did work a few weeks ago, but now I can't read the file anymore:

[N48E008.SRTMGL3.hgt.zip](https://github.com/mvdnes/zip-rs/files/4530843/N48E008.SRTMGL3.hgt.zip)

Do you have any idea what's wrong with the ZIP file?

**Comment by mvdnes** [comment]
With the default options, this file should read just fine as it is the default 'deflate' compression.
You can test this by downloading the repository and running `cargo run --example extract -- N48E008.SRTMGL3.hgt.zip`.

How are you trying this?

**Comment by fschutt** [comment]
```rust
fn get_unzipped_heightmap(input: Vec<u8>, file_path: PathBuf) -> Result<Vec<u8>, Error> {
    use std::io::Read;

    // Unzip the file
    let reader = ::std::io::Cursor::new(input);
    let mut zip = ::zip::ZipArchive::new(reader).map_err(|e| Error::Zip(file_path.clone(), e))?;

    // Take the first file (each heightmap zip file only contains one file)
    let mut file = zip.by_index(0).map_err(|e| Error::Zip(file_path.clone(), e))?;
    let mut file_buf = Vec::<u8>::new();
    file.read_to_end(&mut file_buf).map_err(|e| Error::UnzipError(file_path, e))?;
    Ok(file_buf)
}
```

If I run the `extract` sample, it does work, I can unzip the file. If I use the above code, it doesn't. Strange.

**Comment by mvdnes** [comment]
What do you have for zip-rs in your Cargo.toml file?

**Comment by fschutt** [comment]
`zip = { version = "0.5.5", default-features = false }`

Oh, I think it's because of the `default-features = false`. I usually add that automatically for all crates.

Thanks for the hint.
