### ISSUE TITLE
concurrent reads

### ISSUE THREAD

**Issue by mark-buer** [mvdnes/zip-rs#14]
Hello Maintainer,

Firstly, thank you for creating and maintaining this library!

Secondly, are you interested in adapting this library to support concurrent reads?

For my application, I need to read entries (at random) from a zip file over an extended period of time. The reads might be concurrent, and might be interleaved (read a few bytes from zip entry A, then a few bytes from zip entry B, then A again, etc).

The current API shape makes this use-case impossible without creating multiple `ZipArchive`s.

I've [hacked the code to accomplish my goals](https://github.com/booktrack/zip-rs/compare/master...booktrack:concurrent-read), and thought I'd share it here in case you or any library users are interested in doing something similar.

I'd rather not maintain a separate fork of this library just to suit my use-case if it can be avoided, so if there is interest in incorporating any kind of support for concurrent reads, I'm happy to help out.

If there is no interest, please don't hesitate to close this issue.

**Comment by mvdnes** [comment]
I would be very interested in this.
The problem I had however was keeping track of the position in the files. I did not want to do a seek for every write just in case someone else had modified the position of the file object.

Could you please explain how you tackle the problem of getting two views into one file?

**Comment by mark-buer** [comment]
I tackled the "two views into one file" problem by moving the problem onto the consumer of the API.

In my hacky code, the API consumer is allowed to create multiple concurrent `Read`ers into the decompressed data, albeit at the cost of needing to provide multiple source `Read`ers; a source `Read`er must be provided per decompressed data `Read`er created.

With such an API shape, it would no longer be necessary for the `ZipArchive` to own the source `Read`er. Instead, it could mutably borrow it while parsing the metadata.

If the decompressed data `Read`ers implement `into_inner()` (like [this example from BufReader](http://doc.rust-lang.org/stable/std/io/struct.BufReader.html#method.into_inner)), it would allow the API consumer to "reuse" the source `Read`ers as needed. Thus, it would still be possible to use a single source `Read`er to parse and read the entire zip container in a sequential manner; the API consumer would need to repeatedly use `into_inner()` to retrieve and reuse the source `Read`er for the next operation.

It would _also_ be possible to do more exotic things like described in my original comment. In that case, the API consumer could use multiple source `Read`ers to concurrently read from multiple decompressed streams at once. The multiple source `Read`ers might be created on demand, or might be maintained in a pool, or might be multiplexed from a single `Read`er (that might make an interesting library!) or whatever. How the API consumer manages these source `Read`ers isn't really a concern of the API itself.

I feel like I struggled to articulate this, I hope it makes sense?

**Comment by mvdnes** [comment]
It makes a lot of sense.

I do not have the time to implement such a thing, and still don't know what the best approach is.
Providing new Readers could give some weird effects when the wrong file is passed for example.
But I am always interested in hearing more ideas!

**Comment by icefoxen** [comment]
I was thinking of how to solve this problem and came to a similar solution: each handle to the zip file has its own `Read`er, be it a file handle or whatever, and the `ZipArchive` itself just contains shared data like the index and such.  You could even (optionally) wrap it in an `Arc` and have each handle hold a reference to it, so there's no lifetime dependencies.

**Comment by icefoxen** [comment]
Experimental implementation of this at https://github.com/icefoxen/zip-rs/commit/6f15148ba12aa0bcab25b10efb8baff0837b547d , but see the commit notes for caveats.

**Comment by icefoxen** [comment]
Rambling a little bit, but what I propose is taking the `ZipArchive` -> `ZipFile` structure and breaking it apart a little further.  First we would have a `ZipHeader` which contains the file metadata the `ZipArchive` does now.  Then we have a `ZipArchive` that contains the `Read` object containing the source of the data, and from that you could create a `ZipFile` object that consumes the `ZipArchive`, but can be turned back into it with `into_inner()`.  There could also be a version of a `ZipFile` that just borrows the `Read` object for when that's all you need.

The idea is basically you could share a `ZipHeader`, so you only need to parse the zip file's header data once, but could then open a file multiple times from multiple different threads and read it independently.

**Comment by mvdnes** [comment]
I love the idea of having this feature, but do not know if it is very practical.

Especially since I think the user could also do one of the following things:
* Copying the decompressed file and keeping multiple cursors on it
* Opening the ZipArchive multiple times (by calling `ZipArchive::new(...)`)

Passing a reader object to any of the functions would be a no. This may introduce very confusing bugs for users, and is hard to detect at the library side.

One other possibility is to hand out Cursor like objects to a user. In the case of a deflated file this would be easy, by simply seeking to the correct location. The deflate (and bzip2) case would be harder, as we also need to keep track of the decompression context.

@icefoxen: I do want to take a look at your code, but since the formatting is changed I have a hard time to see the changes. Could you undo them, or split them in separate commits?

**Comment by icefoxen** [comment]
@mvdnes Sorry 'bout that, here's a somewhat more cleaned-up version with just the relevant changes: https://github.com/icefoxen/zip-rs/commit/a52af55cb707af9d4367e03f1b6c843ec4bf22f6

**Comment by spease** [comment]
Was poking around to see if this was possible...would be nice to have this.

**Comment by mvdnes** [comment]
Closing this.
I think opening a ZipArchive multiple times is the best option for now, as zipfiles are not parallel by nature.

I have added an `dervice(Clone)` for ZipArchive, which enables a clone if the reader supports it. This will not be the case for a file, but will be for a cursor.

**Comment by clouds56** [comment]
I'm concerning about the performance on clone,
```rust
#[derive(Clone, Debug)]
pub struct ZipArchive<R: Read + io::Seek>
{
    reader: R,
    files: Vec<ZipFileData>,
    names_map: HashMap<String, usize>,
    offset: u64,
    comment: Vec<u8>,
}
```

Now the `ZipArchive` save lots of metadata in the struct (all are not `Cow`), clone seems to consumes lots of resource.

If I read `pub fn by_index<'a>(&'a mut self, file_number: usize) -> ZipResult<ZipFile<'a>>` correctly, the `ZipFile<'a>` keeps only immutable reference of `ZipArchive` except `Take<R>`,

Could we implement `ToOwned` for `ZipFile<'a>` and `ZipFileReader<'a>` for R: Clone?
so that we could write 
```rust
let mut all_files = vec![];
for i in 0..zip.len() {
    let file = zip.by_index(i)?.to_owned(); // would not complain about zip being borrowed
    all_files.push(file); // save file for future (concurrently) use
}
```

I could help PR here.

**Comment by DavidBM** [comment]
Hi! @elpiel and me are implementing an clone of unzip in rust. It would be nice to have this parallelization features and would love to help in making it happen. What do you need? How can we help? Is there any problem with the solution proposed by @clouds56? @mvdnes

**Comment by mvdnes** [comment]
I am sorry, but I am no longer actively maintaining this project.

**Comment by DavidBM** [comment]
I understand. Would you accept help for maintaining and developing the crate?
@elpiel and me are interested in helping and evolving it. You can check our gitter channel. https://gitter.im/rzip/community?at=5dc5bb63add5717a88d1d2c0

In any case, if you were open to add more maintainers, we can go through pull requests, issues, etc and try to keep the development active.

**Comment by DavidBM** [comment]
Just tagging you as I just realized that I didn't in the first message https://github.com/mvdnes/zip-rs/issues/14#issuecomment-552197585 @mvdnes . 

What do you think? Would you be open to new maintainers?

**Comment by mvdnes** [comment]
Instead of adding new maintainers, I think forking the project would be better. I could later transfer the crates.io.

**Comment by DavidBM** [comment]
ok! Then let's do that. If we reach a point where it makes sense to transfer the crates.io, we will show you the code/changes and then we can see what to do. Thanks!
