### ISSUE TITLE
Establish an MSRV (minimum supported Rust version)

### ISSUE THREAD

**Issue by rylev** [mvdnes/zip-rs#158]
We currently only run CI on the latest stable. We should establish a minimum version we want to support, ensure we run CI on that version and advertise that in the README.

**Comment by Plecra** [comment]
The crates written in 2018 edition syntax, so we couldn't drop below 1.31.0

However, [`miniz-oxide`](https://github.com/Frommi/miniz_oxide) (`flate2`'s Rust backend) uses `std::convert::{TryFrom, TryInto}` from 1.34.0.

[We also use `#[non_exhaustive]`](https://github.com/mvdnes/zip-rs/blob/master/src/types.rs#L3) from 1.40.0, but it's not in the public API and could be removed without any probem. Without it, we can `cargo test` on 1.34.0

**Comment by rylev** [comment]
Only 3% of those who responded to the Rust survey said they use a previous stable version, so I don't think we need to be ultra conservative. I did an informal survey once of production users of Rust, and for only a very small percentage didn't track Rust releases within 6 weeks. I think having a hard minimum of 4 releases below the current stable release is pretty good as this gives users 6 months to upgrade. That being said, if it's not too inconvenient we can go back further.

**Comment by Plecra** [comment]
How about treating MSRV changes as a minor version bump? I don't expect to need to go above 1.34.0, but like you said, there's no need to be strict about it.

**Comment by rylev** [comment]
Are we also ok with having MSRV be _at least_ 4 below current stable and only breaking that if there's a security issue or a dependency forces us to?
