### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by rylev** [mvdnes/zip-rs#164]
I believe we should add a code of conduct for contributing to this repo. All repos that are open sourced through the company I work for include one automatically, and it can help settle disputes when someone is not acting in a collaborative manner. It's simply a statement in writing of what I hope is already a core value of this project: respect for others.

**Comment by Plecra** [comment]
Is there a template you'd like to use?

**Comment by rylev** [comment]
I think the contributor covenant has a [template](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) that captures what I had in mind. Thoughts?

**Comment by Plecra** [comment]
Hm... I like the promises it makes, but I don't really want to commit to taking care of that email address. It seems directed towards projects with a community around them, where moderation would be important. It should be enough for the active contributors to keep the standards.

**Comment by rylev** [comment]
Yea I hear you. Since this project only exists as a public repo on GitHub I don’t see how harassment could occur and not be open to public moderation from the maintainers. That being said in the off-chance someone has a concern they’d rather not make public it is nice to have a point of contact that’s not public. I’m happy to volunteer my email address as the point of contact just in case. Thoughts?

**Comment by Plecra** [comment]
If you're alright with that, then by all means ^^
