### ISSUE TITLE
Can ZipArchive::by_index/by_name not be mut?

### ISSUE THREAD

**Issue by icefoxen** [mvdnes/zip-rs#18]
It just feels like a weird abstraction break to have a fundamentally read-only operation require the ZipArchive to be mutable, when all that's ever changing is the internal reader object which won't be shared by anything else anyway.  It seems like wrapping it in a `RefCell` would let you pretend everything is immutable, since the API is entirely immutable anyway.

I'm not sure this is a good or feasible idea, it's just a suggestion.  I might try implementing it sometime and see how it works out.

**Comment by mvdnes** [comment]
If you have a nice implementation I would be happy to take a look at it and merge it!
For the time being I have no real interest in implementing this myself, but would like it if this was fixed.

**Comment by icefoxen** [comment]
Ok, I'll play around with it and see what I can come up with.

**Comment by icefoxen** [comment]
Upon playing around, this might not be doable without changing how a `ZipFileReader` works somehow.  Even if you try to wrap the `ZipArchive`'s reader up in a `RefCell`, if you try to create two `ZipFileReader`'s you will end up with two mutable references both trying to screw with the underlying reader.  You really need an entirely separate reader for each `ZipFileReader`, each preserving where they are pointing in the file.  But you can't, generally, clone something implementing `Read`.

You can try faking it with a single reader by having each `ZipFileReader` remembering where its file offset is, seeking to that and updating it every time you read from the `ZipFileReader`, and maybe using unsafe to convince everything that this doesn't count as "mutation".  But I don't know about much the innards of this and it would basically break the current model which is to have a single `Read` type and just wrap that in layers of translation.

**Comment by mvdnes** [comment]
Come to think of it, this seems closely related to issue #14. Feel free to continue the discussion there.
