### ISSUE TITLE
Release 0.5.7

### ISSUE THREAD

**Issue by rylev** [mvdnes/zip-rs#180]
We've made enough small non-breaking changes, that I think releasing 0.5.7 sounds like a good idea. @Plecra thoughts?

**Comment by Plecra** [comment]
Agreed! I'd like to wrap up #178 first, and make a few additions to the documentation.

Would you mind adding that test? I imagine it should be fairly simple

**Comment by Plecra** [comment]
Add #181 to that, which I think is quite urgent

**Comment by robmv** [comment]
Just a small request. Can the release process include creating a tag on the repository? This is useful when you want to compare changes between releases, or to know what new fixes on master aren't still released.

**Comment by Plecra** [comment]
I'd say we're ready to finalize the release. @mvdnes , how do you want to handle this?

**Comment by mvdnes** [comment]
I see that we have a request for a tag. If you create one, I will publish that version to crates.io.

**Comment by Plecra** [comment]
https://github.com/mvdnes/zip-rs/tree/v0.5.7

@rylev , that look good to you? If so, I'm happy for it to be published

**Comment by rylev** [comment]
Let's do it! Thanks for handling this chore! For reference for anyone else, here's a [diff between 0.5.6 and 0.5.7](https://github.com/mvdnes/zip-rs/compare/18bece201c15ec78f5f46d51c1192aeb393742f2..v0.5.7) 

@mvdnes we're ready for you to pull the trigger! 😊

**Comment by mvdnes** [comment]
Done :+1:

**Comment by rylev** [comment]
Thanks!

@Plecra shall we start a tracking issue for 0.6?

**Comment by Plecra** [comment]
Sure, it wouldn't hurt. We've got the milestone for now, but it would be good to explore the changes we want to make.

Briefly, (I'd say) we should be making iterative improvements on the current API, without many major changes to the internals.

**Comment by BenjaminRi** [comment]
Thank you all for the good work and congratulations to @Plecra and @rylev for the first release since taking over.

Thanks to this new release, I was able to scrap my fork and depend on your zip crate, because you merged the ZipCrypto stuff.
