### ISSUE TITLE
Expose CRC-32 location.

### ISSUE THREAD

**Issue by n3vu0r** [mvdnes/zip-rs#189]
We're currently working on memory-mapped file support for the [`ndarray-npy`](https://github.com/jturner314/ndarray-npy/issues/36) crate. We want to support mutable access for uncompressed `.npy` files within an `.npz` (Zip) file. This requires to recompute the CRC-32 checksum. Would it be possible to simply expose the CRC-32 slice offset with a method like `ZipFile::crc32_start() -> u64`?

**Comment by n3vu0r** [comment]
Oh, it seems you have already `ZipFile::header_start() -> u64` in the master branch. That would do it as well and is even better.

**Comment by n3vu0r** [comment]
Is it safe to assume the CRC-32 checksum is stored only in the local file header? Or can it also be stored in the central directory file header? The data descriptor seems not to be supported, what is its use case?

**Comment by n3vu0r** [comment]
Sorry for the mess. It seems the central directory file header is primarily used. I think then for our use case only a `ZipFile::central_header_start() -> u64` would be missing.

**Comment by Plecra** [comment]
This is certainly an awkward use case to support. I'm not a fan of including parsing in the main API, but would you find a separate crate for the parsing logic useful?

**Comment by n3vu0r** [comment]
I understand that this would be of limited use and doesn't really belong in the main API. What do you mean with separate crate? Do you have plans for a crate that is designed to expose parsing details? That would do it, of course. On the other hand, you have already `header_start()` and `data_start()`. Doesn't `central_header_start()` nicely complement on this? It's basically a one-liner at line 436 of `read.rs`: `let central_header_start = reader.seek(io::SeekFrom::Current(0))?;`.

**Comment by Plecra** [comment]
The maintainer of the crate was recently changed, and we've only made semver-co partible changes so far. I'm hoping to remove the `*_start` methods from the next release, in favour of a more practical parsing API for users with specific needs.

@rylev, what do you think of a small 0.5.8 release adding this?

**Comment by rylev** [comment]
I'd rather provide a more comprehensive parsing solution rather than this one-off function. That being said, it's a small change that we could technically revert in future versions.

**Comment by Plecra** [comment]
I completely agree. There doesn't seem to be any harm in fleshing out the 0.5 API as it is since it'll take so little work 😊

**Comment by n3vu0r** [comment]
Thanks a lot, much appreciated.
