### ISSUE TITLE
0.5.7 breaking change

### ISSUE THREAD

**Issue by Luminoth** [mvdnes/zip-rs#191]
Hi, the change to deprecate sanitized_name() is a breaking change for anyone using #[deny(warnings)], and using an unpinned version of "0.5" in Cargo.toml is pulling that in. Could you make this a minor version update to reflect that you've made a breaking change to the API?

**Comment by Plecra** [comment]
Deprecation is meant to be used for discouraging the use of APIs without introducing breaking changes. It's used the same way by `std`, and I'm afraid it's the only tool we have for that.

You're probably aware, but you can always `allow(deprecated)` on a crate- or item-level.

**Comment by Luminoth** [comment]
I'm not saying don't deprecate, I'm saying deprecation is a patch-level breaking change (you literally broke my build with this release) and this update should have been a minor version bump. If it helps, here is how this is defined by semver itself (https://semver.org/):

```
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
```

```
Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.
```

```
How should I handle deprecating functionality?

Deprecating existing functionality is a normal part of software development and is often required to make forward progress. When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) issue a new minor release with the deprecation in place. Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.
```

**Comment by rylev** [comment]
Rust's deprecation semantics don't include warnings. Meaning while Rust itself guarantees backwards compatibility between versions, this does not extend to warnings with `deny(warnings)` set. We, along with most crates in the Rust ecosystem, adopt this same policy.

**Comment by Luminoth** [comment]
Yes, I'm aware of the policy with regards to minor release deprecation. You broke it on a patch release and that is the problem. Rust itself does not do that and, as far as I am aware, never has.

**Comment by rylev** [comment]
We're pre-1.0 so effectively we don't have patch releases. We only have non-breaking minor and breaking major releases until we reach 1.0. This is also very common in the Rust ecosystem.

**Comment by Luminoth** [comment]
*sigh* ok
