### ISSUE TITLE
0.5.7 Breaking change: From<ZipError> is not implemented for `std::io::Error`

### ISSUE THREAD

**Issue by pftbest** [mvdnes/zip-rs#192]
Before commit 18bece201c15ec78f5f46d51c1192aeb393742f2 there was an impl:

```Rust
impl convert::From<ZipError> for io::Error
```

which is missing now. This is a breaking change, crate "rogcat" is affected by this.

**Comment by Plecra** [comment]
Apologies! We'll fix this promptly

**Comment by pftbest** [comment]
Thanks!
