### ISSUE TITLE
0.5.7 breaking change: Previously exhaustive ZipError matches no longer exhaustive

### ISSUE THREAD

**Issue by MaulingMonkey** [mvdnes/zip-rs#193]
I have code mapping between error types which is no longer exhaustive:
```rust
match imp.writer.add_directory(path, FileOptions::default()) {
    Err(ZipError::FileNotFound)             => return Err(VfsError::FileNotFound { path: path.into() }),
    Err(ZipError::Io(e))                    => return Err(VfsError::IoError(e)),
    Err(ZipError::InvalidArchive(e))        => return Err(VfsError::IoError(io::Error::new(io::ErrorKind::InvalidData, e))),
    Err(ZipError::UnsupportedArchive(e))    => return Err(VfsError::Other { message: e.into() }),
    Ok(())                                  => {},
}
```
```
    |
46  | match imp.writer.add_directory(path, FileOptions::default()) {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ patterns `Err(PasswordRequired)` and `Err(InvalidPassword)` not covered
    | 
```

It might be worth marking ZipError [`#[non_exhaustive]`](https://doc.rust-lang.org/reference/attributes/type_system.html) going forward, or adding a `#[doc(hidden)] _DoNotFullyMatch` variant to ZipError to avoid similar breakages in the future.

**Comment by Plecra** [comment]
Whoops! That was a definite oversight. We were considering using a custom error branch for the new methods already, and I'll get those changes out on the 0.5 version instead.

@rylev, that'd mean changing the signatures of the new zipcrypto methods, making 0.5.7 a bad target for anyone to use. Could we yank it now?

**Comment by rylev** [comment]
I wouldn't yank it since it's a valid version on its own. Marking the enum as `#[non_exhaustive]` should take care of the issue.

**Comment by Plecra** [comment]
It wouldn't? Anyone depending on version < 0.5.7 already has potentially been broken by the extra variants. We *can't* add them to a 0.5 version backwards-compatibly

**Comment by rylev** [comment]
Ah yes you're right. I still not sure yanking is the right approach, but perhaps it is.

**Comment by Plecra** [comment]
It's kinda okay to just publish 0.5.8 and cross our fingers that users skip over 0.5.7. the version number would just be a lie, and I think yanking quickly might be the least bad option

**Comment by rylev** [comment]
Ok let's push out 0.5.8, and yank 0.5.7. Is this fix to change change the new zipcrypto functions to return a different error type?

**Comment by Plecra** [comment]
I was thinking of returning a `ZipResult<ZipFile, InvalidPassword>>` from the crypto function, yea. We'd have to replace `PasswordRequired` with an `UnsupportedArchive`

**Comment by BenjaminRi** [comment]
Oops, that was my mistake. I didn't think about the possible consequences of adding another value to this enum. I think returning `UnsupportedArchive` is misleading because the archive is in fact supported. But I guess it does fix the compilation breakage.

If you remove the `InvalidPassword` error, you also have to fix the test which explicitly expects this error code on using a wrong password: https://github.com/mvdnes/zip-rs/blob/master/tests/zip_crypto.rs#L62

However, I do wonder: Why did you release this as a patch? You did major changes in the library and the entire ZipCrypto part was added. I think this warrants at least a minor version increase, doesn't it? A patch is a small change to fix some minor stuff, not an addition of significant refactorings and new features.

**Comment by MaulingMonkey** [comment]
> yanking

FWIW, I've added `Err(_) => {}` fallbacks such that my code in question should be able to handle both 0.5.7 and a future 0.5.8 with the new cases fixed, so I have no strong opinions on this.

> Why did you release this as a patch?

0.x.y often guarantees *nothing* via semver.  By the other common standard, the intent here was fine - that standard being 0.major.minor.patch, with this release being a minor version bump, where extensions to the API and internal backwards-compatible changes would be appropriate.
