### ISSUE TITLE
0.5.8

### ISSUE THREAD

**Issue by Plecra** [mvdnes/zip-rs#194]
We've got a couple more small changes to make to 0.5

# Breakages

- [x] #192
- [x] #193

# Missing Features

- [x] #189

**Comment by Plecra** [comment]
I'll be able to sort these out on next Monday. It'd be nice to fix the breakages quickly though, so I'd happily review a PR sooner

**Comment by Plecra** [comment]
@mvdnes , it'd be great if you could publish 0.5.8 (https://github.com/mvdnes/zip-rs/releases/tag/v0.5.8) and yank 0.5.7 ASAP.

In case you hadn't seen, I'd merged some breaking changes and there was no way for us to make 0.5.7 a semver-compatible release. Since any code depending on it is liable to break, we're completely replacing it with 0.5.8

**Comment by mvdnes** [comment]
Done :+1:
