### ISSUE TITLE
set comment/unix_mode/last_modified fields when creating a zipfile

### ISSUE THREAD

**Issue by ultimaRatio** [mvdnes/zip-rs#20]
Hi, 

It's not an issue, just a question. 
I've try to set unix_mode and last_modified fields when creating a file with ZipWriter, with no success.

After a short review, setting this two fields doesn't seem too complicated (probably in write_central_directory_header and write_local_file_header), maybe it is not implemented because no one has never needed it ? :-)

**Comment by ultimaRatio** [comment]
ok, i've answer my own question with little a fork :-)

**Comment by mvdnes** [comment]
I welcome all pull requests, so if you have something that works well I look forward to your changes!

**Comment by ultimaRatio** [comment]
ok, but it's just a quick'n'dirty solution, nothing fancy.
By the way, setting unix_mode to 0 is not the best default value in *nix, even if it's doesn't problematic.
