### ISSUE TITLE
Can ZipFile implement Seek?

### ISSUE THREAD

**Issue by icefoxen** [mvdnes/zip-rs#25]
I feel like this might have been asked before; if so, I apologize.

Is it possible for the `ZipFile` type to implement the `Seek` trait?  I'm honestly not sure, but it would be useful to have the option, even if it involves iterating through the whole file decompressing it on the fly.

Thanks.

**Comment by icefoxen** [comment]
Related to issue #14 :/

**Comment by mvdnes** [comment]
This is not actually related to #14.
For compressed files, it would not be practical to implement seek. Zlib only allows a stream to move forward. So unless you decompress the entire file in memory, you cannot go backwards.
For small files this would be OK, but this library should also take files into account that could be very large.

If you want to implement this yourself, you can read the file into a Vec, and then wrap in in a [Cursor].

[Cursor]: https://doc.rust-lang.org/stable/std/io/struct.Cursor.html

**Comment by zumoshi** [comment]
@mvdnes What about seeking only for files using `Store` (i.e. no compression)
My use case is bundling some metadata with an encrypted file (which won't compress well anyway), but I need seeking inside that file. Would you recommend another file format or is it possible to get a seekable slice of the zip file from this library?
