### ISSUE TITLE
Zip-RS extract.rs example absolute extraction paths

### ISSUE THREAD

**Issue by noxrnet** [mvdnes/zip-rs#27]
The `examples/extract.rs` script does not protect against files being extracted to arbitrary directories outside the current directory. Whilst it appears some effort is made to prevent path traversal from zip entry filenames containing `../` (in `sanitize_filename`), this does not protect against entry filenames with absolute paths.

For example, a zip entry with a filename of `/tmp/outfile` will be extracted to `/tmp/outfile` instead of `./tmp/outfile`. See [zip_3_absolute_directory.zip](https://github.com/mvdnes/zip-rs/files/768404/zip_3_absolute_directory.zip) for an example of this.

Whilst this is not an issue with the zip-rs library itself, having an insecure example which other developers may copy is less than ideal.

**Comment by mvdnes** [comment]
Thanks! This was indeed an issue I was trying to avoid. Should be fixed now.
