### ISSUE TITLE
ZipWriter doc sample fails to write

### ISSUE THREAD

**Issue by stanmihai4** [mvdnes/zip-rs#28]
Running the ZipWriter sample exits with an error:

> ZipWriter drop failed: Io(Error { repr: Custom(Custom { kind: WriteZero, error: StringError("failed to write whole buffer") }) })
> Result: Err(Io(Error { repr: Custom(Custom { kind: WriteZero, error: StringError("failed to write whole buffer") }) }))

**Comment by stanmihai4** [comment]
From what I see, using `SeekFrom::End(0)` in `finish_file` for a buffer moves the position the the end of the buffer, not the last written byte.

**Comment by stanmihai4** [comment]
Added PR#29

**Comment by mvdnes** [comment]
Resolved with #29, thanks for submitting this report!
