### ISSUE TITLE
Issues unzipping file

### ISSUE THREAD

**Issue by gnieto** [mvdnes/zip-rs#32]
I'm using this crate to decompress some ZIP files and I'm having issues to decompress this file (the extension is APK, but it's a ZIP file): https://apkpure.com/aliexpress-shopping-app/com.alibaba.aliexpresshd

I've dug a little in the problem and it seems that it crashes when it tries to parse extra fields. On the 34th file, the `extra_field_length` field has 3 as a value, which provokes that `extra_field` ends with a buffer of 3 positions (in particular, the buffer is [0, 0, 0]).

I've checked the specification and it seems that extra field should contain pairs of HeaderId (u16) and data size(u16), but the given buffer is not multiple of 4, which provokes that `parse_extra_field` function returns an Err, which is propagated up to the `zip::ZipArchive::new` method.

It seems like this ZIP is not well formed, but other ZIP utilities on my computer are able to decompress it. If I comment the calls to `parse_extra_field` the file can be decompressed properly. Do you know if can be related to some of the ZIP extensions that you state on the README that are not yet supported?

Is there anything that I can do to help solving this issue? 

Thanks

**Comment by mvdnes** [comment]
Thanks for reporting the issue! 👍
