### ISSUE TITLE
Does not support ZIP64

### ISSUE THREAD

**Issue by pkgw** [mvdnes/zip-rs#39]
I just ran into a problem because I have a Zip file with ~80000 files in it, and zip-rs can't handle it since you need to support ZIP64 to work with archives with more than 65535 files.

This is pretty urgent for me so I am going to see what I can do to get my use case working. It seems like it would be good to have an issue open to track the general task, though, so here we are.

**Comment by pkgw** [comment]
[Here's a branch](https://github.com/pkgw/zip-rs/tree/pr-basic-zip64) that fixes my proximate problem.

**Comment by mvdnes** [comment]
This was one of the features I have been willing to add! Thanks for your initial work.
Unfortunately I do not have a lot of time at the moment to read the spec. I would greatly appreciate it if you could also add some tests.

**Comment by Kixunil** [comment]
That branch works for me and solves my problem, so thank you very much! I'd like to help with further development but I'm low on time. :'(

Good luck!

**Comment by mvdnes** [comment]
Closed in #44
