### ISSUE TITLE
Implement core::convert::From so by_name can be used in try!()

### ISSUE THREAD

**Issue by ndarilek** [mvdnes/zip-rs#4]
Getting the following:

   Compiling gtfs v0.0.1 (file:///C:/users/nolan/Projects/Gtfs-rs)
<std macros>:6:1: 6:32 error: the trait `core::convert::From<zip::result::ZipErr
or>` is not implemented for the type `std::io::error::Error` [E0277]
<std macros>:6 $ crate:: convert:: From:: from ( err ) ) } } )
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:1:1: 6:48 note: in expansion of try!
src\feed.rs:19:16: 19:58 note: expansion site

Attempting the following:

    let file = try!(self.archive.by_name("agencies.txt"));

New to Rust so perhaps I'm missing something. I'd like to punt all zip errors up the callstack.

Thanks.

**Comment by mvdnes** [comment]
One way to fix your problem is by returning a ZipResult in your function, that does have an impl the other way around: `impl convert::From<io::Error> for ZipError`.

Nevertheles I like your suggestion and will push a commit with this addition soon

**Comment by ndarilek** [comment]
Excellent, works. Thanks!
