### ISSUE TITLE
file truncated when decompressing DEFLATE

### ISSUE THREAD

**Issue by Gjum** [mvdnes/zip-rs#43]
I'm using version `0.2.5`: `"checksum zip 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = "12143b8b0e8d215391a2c6362d54b482589cb469b0fa4d047c42067cd4bcb311"`

## Reproducing
Get [test.zip](https://github.com/mvdnes/zip-rs/files/1133160/test.zip), then run these scripts:
https://gist.github.com/Gjum/f7e95799183b5710a6c9341463e167a0

zip-rs stops mid-file and leaves the remaining bytes unchanged,
while Python's deflate module successfully extracts the whole file.

The first omitted byte is `0xA0` in this example. Many other similarly created files I tested this with get truncated too, at different byte offsets and different first omitted byte values.

`test.zip` was created using Python's `zipfile` module with its DEFLATE method. When using STORE, everything works well.

## Expected result
output from reproduce.py, see [test-py.out](https://github.com/mvdnes/zip-rs/files/1133161/test-py.txt) for the full output
```
7A 00 01 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 7C A0 06 F0 23 <- difference starts here
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7C 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7E 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7E 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7E 00 02 F0 00 00 00 00 7F 00 8B F1 00 00 00 00 23 
7E 00 02 F1 00 00 00 00 00 00 00 00 00 00 00 00 23 
```

## Actual result
output from `reproduce.rs`, see [test-rs.out](https://github.com/mvdnes/zip-rs/files/1133162/test-rs.txt) for the full output
```
7A 00 01 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 00 00 00 00 23 
7B 00 02 F0 00 00 00 00 00 00 00 00 7C 00 00 00 00 <- difference starts here
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... all zeroes from here
```

**Comment by mvdnes** [comment]
Your code does not account for partial reads.
In rust, ` try!(file.read(contents));` is not guaranteed to have read the whole file. Since you know the exact number of bytes to be read, you should replace it with `try!(file.read_exact(contents));`. If you do not know it, make `contents` a `Vec<u8>` and use `read_to_end`.
