### ISSUE TITLE
Why is `ZipArchive::new()` fallible?

### ISSUE THREAD

**Issue by sanmai-NL** [mvdnes/zip-rs#45]
[The documentation](https://docs.rs/zip/0.2.6/zip/read/struct.ZipArchive.html#method.new) doesn’t say why this method could fail. I can't think of the reason. Could you explain and document that?

**Comment by mvdnes** [comment]
The usual reason would be for Zip files that are unsupported (e.g. due to encryption) or when they are malformed.

**Comment by sanmai-NL** [comment]
Thanks for the response. I'm sorry, I overlooked `ZipArchive` is only for reading _existing_ ZIP data. I thinks the docs are clear enough after all. Closing!
