### ISSUE TITLE
Support of files more than 4Gb

### ISSUE THREAD

**Issue by seb-odessa** [mvdnes/zip-rs#49]
Hi,
I was faced with this issue while worked on fb2 library tool.
E.g fb2-545000-549999.zip has  5190592358 bytes length and won't be processed by the zip-rs.
I have attached torrent file as a target for reproducing.

**Comment by seb-odessa** [comment]
Fix of big file reading in [pull request](https://github.com/mvdnes/zip-rs/pull/50)

**Comment by mvdnes** [comment]
In the current version most of Zip64 is now implemented.
Please re-open an issue if you are still missing items.

Sorry that I did not respond to your issue earlier!
