### ISSUE TITLE
Suggest to yank 0.2.9

### ISSUE THREAD

**Issue by laumann** [mvdnes/zip-rs#56]
I've been thinking that the 0.2.9 should have been a 0.3.0 as the `deflate` feature is a breaking change. Users of <0.2.9 can't necessarily use 0.2.9 and vice versa users of 0.2.9 can't necessarily use <0.2.9. It's just a suggestion though, if you don't agree feel free to close this issue :smile: 

(I created this issue to avoid hijacking #23 anymore than I already have...)

**Comment by mvdnes** [comment]
Good idea, I have done just that! 👍
