### ISSUE TITLE
Can not read certain ZIP files on windows

### ISSUE THREAD

**Issue by Laaas** [mvdnes/zip-rs#61]
Certain ZIP files when read on windows cause an error. This does not happen with windows explorer's built-in ZIP reader, 7-zip, etc., however, 7-zip gives a warning saying "Headers Error".

The error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 87, kind: Other, message: "The parameter is incorrect." })', libcore\result.rs:945:5
error: process didn't exit successfully: `target\debug\zip-rs-error.exe` (exit code: 101)
```

The version of windows used is Windows 7 Ultimate. The error does not occur on linux.

The code:
```rust
extern crate zip;

use std::fs::File;
use zip::read::ZipArchive;
use std::io::{Read, Cursor};

fn main() {
    let mut buf = Vec::new();
    File::open("archive.zip").unwrap().read_to_end(&mut buf).unwrap();
    let _archive = ZipArchive::new(Cursor::new(buf)).unwrap();
}
```

[The unreadable archive](https://github.com/mvdnes/zip-rs/files/1727819/archive.zip)
[Test case](https://github.com/mvdnes/zip-rs/files/1727804/zip-rs-error.zip) (also contains the unreadable archive)

**Comment by mvdnes** [comment]
Thanks for the issue. Windows and Linux handle invalid dates differently. This caused the Zip to be rejected on Windows only.

Now, a default is used instead.

**Comment by Laaas** [comment]
Thank you! Until now I had to use vbscript to extract zip files on windows to work around this problem :nauseated_face:.
