### ISSUE TITLE
Add extract_all to ZipArchive

### ISSUE THREAD

**Issue by spease** [mvdnes/zip-rs#66]
Another convenience function request, it'd be nice if there were an extract_all method on ZipArchive that you could specify a path to extract files to. Basically like the extract.rs example. This makes more sense than each user of the library that wants to extract a zip file having to replicate that code themselves.

**Comment by mvdnes** [comment]
I think the main use-case is to use this library for reading/writing files in memory, not extracting them to disk. There are a lot of excellent tools to do that already. I would like to leave it with just the example as a hint for this implementation, rather than doing it for the other users.

**Comment by dsherret** [comment]
@mvdnes what tool would you recommend?

This seems to be the most maintained library for unzipping files. Perhaps this should be added nowadays?

**Comment by spease** [comment]
This is also the most discoverable library for this purpose...from a language ecosystem POV, it’s ideally named to be a general-purpose package.

“I want to extract a zip, but I don’t want to depend on a specific zip application being installed” is a not uncommon use case I’d foresee. This would also open the door to more sophisticated implementations later on, eg if a private API eventually allowed it then the function could automatically launch helper threads to decompress multiple files at once.

I’m not actively using this package anymore though due to moving on from the project I was using it for.

**Comment by rylev** [comment]
This has been implemented (though not yet released on crates.io): https://github.com/mvdnes/zip-rs/pull/116
