### ISSUE TITLE
Add ZipFile.is_directory()

### ISSUE THREAD

**Issue by vasily-kirichenko** [mvdnes/zip-rs#69]

**Comment by mvdnes** [comment]
The only way I know how to do this is by checking if the filename ends with a '/'. Is this actually a fool-proof way?

**Comment by dbeckwith** [comment]
I don't think that always works. I think sometimes directories can be listed in the zip file without a trailing slash. In which case there is no way to distinguish between a directory and a zero-sized file with the current API.

**Comment by dbeckwith** [comment]
Ah, actually I think I know the problem. I was looking at a zip file created with `zip-rs`. Normally zip files are supposed to terminate directory entries with a slash, but `zip-rs` doesn't enforce this in [`add_directory`](https://github.com/mvdnes/zip-rs/blob/master/src/write.rs#L271).

**Comment by mvdnes** [comment]
I hadn't though of the slash when writing a zip file. I have added some code to ensure directory names will always end in a slash. Thanks for the idea.
