### ISSUE TITLE
Zip file does not work for LÖVE2D

### ISSUE THREAD

**Issue by camchenry** [mvdnes/zip-rs#72]
I program games in Lua using the [LÖVE game framework](https://love2d.org/). I am developing a build tool which will automatically create .love files (just a renamed .zip file) and do a lot of zipping in general. I know that LÖVE uses [PhysicsFS](https://icculus.org/physfs/) for working with zip files.

For some reason, the zip file created by zip-rs will not load with LÖVE, but other zip files created by Info-ZIP or 7-Zip will work with no issue.

I have attached a zip file created by Info-ZIP and one created by zip-rs. The file being zipped is exactly the same. This is a diff of the two files, the one on the left is zip-rs (red), the one on the right is Info-ZIP (green).
![image](https://user-images.githubusercontent.com/1514176/40146389-50f79dbc-5933-11e8-9496-6176c149c926.png)
* [test-info-zip.zip](https://github.com/mvdnes/zip-rs/files/2010984/test-info-zip.zip)
* [test-zip-rs.zip](https://github.com/mvdnes/zip-rs/files/2010985/test-zip-rs.zip)

I have been able to do a workaround by changing the default system byte to Unix, (https://github.com/camchenry/zip-rs/commit/63a3ec3aa9d1f5e3d9169ea06d6724d4d9999b4e) and then it works fine. If I set it to Unix, it seems to load just fine. Even more strange, changing that same byte in zip files generated by other programs seems to have no effect.

**Comment by mvdnes** [comment]
After some debugging I have found the issue. It was a confusion in the 'version made by' and 'version needed' information of the ZIP spec. Appareantly the LOVE2D code was the only one that really checks this field.

Thanks for the report! :+1:
