### ISSUE TITLE
CRC Error on binary files

### ISSUE THREAD

**Issue by tramez** [mvdnes/zip-rs#8]
I'm using zip-rs to compress multiple binary files into one zip.
Zipping some text files works fine, but when I'm doing this with binary files, the CRC is wrong.
Using 7zip I can still extract the data and if I'm testing it with an MP3 file VLC does not emit any errors on the extracted file, thus the data itself is correct.

My zipping code:
```
let mut dir = PathBuf::from(&CONFIG.general.temp_dir);
    dir.push(folder);
    
    if try!(metadata(dir.as_path())).is_dir() {
        
        let output_file = try!(File::create(zip_path));
    	let mut writer = zip::ZipWriter::new(output_file);
        
        for entry in try!(read_dir(dir)) {
            let entry = try!(entry);
            if try!(entry.metadata()).is_file() {
                try!(writer.start_file(entry.file_name().to_string_lossy().into_owned(), zip::CompressionMethod::Deflated));
                let mut reader = try!(File::open(entry.path()));
                let _ = reader.sync_data();
                try!(copy(& mut reader,& mut writer));
            }
        }
        try!(writer.finish());
        trace!("finsiehd zipping");
        Ok(())
    }else{
```

'CRC failed in test.bin File is broken.'

If I use CompressionMethod:Stored -> No compression, everything's fine.

**Comment by mvdnes** [comment]
It seems that the CRC in the output file is fine (unzip -v does not show any errors), but that the problem occurs when reading (extracting) with this library. I will investigate this further.

**Comment by mvdnes** [comment]
Ah nevermind, unzip did not output an error, but 7zip is indeed stricter. It lies in the decoding stage

**Comment by tramez** [comment]
@mvdnes I can't unzip it with the windows internal unzipper, since it is directly aborting because of that problem.

**Comment by tramez** [comment]
Works now, thanks !

**Comment by mvdnes** [comment]
Thanks for the bug report and feedback :+1:

**Comment by GBTEN** [comment]
You Can Extract Bin Files With Universal Extractor
