### ISSUE TITLE
Additional tests

### ISSUE THREAD

**Issue by camchenry** [mvdnes/zip-rs#82]
I was thinking about implementing additional tests and I wanted to get some feedback before implementing anything.

First one I was thinking about was a circular zip test.

1. Zip some arbitrary data with zip-rs
2. Unzip that data with zip-rs
3. Assert that start data == end data

This seems like something that should **always** be true, no matter what. It also seems like a usability issue if zip-rs was somehow able to create a zip file that it couldn't read. This would also provide a good test for fuzzing in the near future.

Additional test ideas are welcome. Thanks.

**Comment by mvdnes** [comment]
Such a test would be a great idea. Feel free to implement it.

**Comment by camchenry** [comment]
Ok, I will try to implement it when I have some time.
