### ISSUE TITLE
Comparatively poor performance (both speed & size)

### ISSUE THREAD

**Issue by Ichoran** [mvdnes/zip-rs#88]
Compared to the `zip` command-line tool, or compared to the standard OpenJDK implementation (which is equivalent), `zip-rs` has poor performance in both senses: it is slow (~3x slower than the standard implementations and equivalent compression), and it has only approximately the worst deflate compression available with zip.

Since compression can be a rate-limiting operation (in my case it is), this is a rather significant drawback.  I realize that a significant part of this is due to deficiencies in `libflate`, but it still is a substantial negative for this crate.  If a native implementation that performs acceptably is too tricky to create, a feature wrapping `libzip` would render the crate usable.

If you find some file of a dozen MB or so and name it `speed.log`, the following will test the performance:

```rust
#[derive(Debug, Clone, Copy)]
pub struct CompressionResult {
    pub dt: f64,
    pub MBps: f64,
    pub shrink: f64
}
impl CompressionResult {
    pub fn new(dt: f64, MBps: f64, shrink: f64) -> CompressionResult {
        CompressionResult { dt, MBps, shrink }
    } 
    pub fn from(dt: f64, old_size: u64, new_size: u64) -> CompressionResult {
        let MBps = ((old_size as f64)/(1024.0*1024.0))/dt;
        let shrink = (new_size as f64)/(old_size as f64);
        CompressionResult {
            dt: (dt*1000.).round()/1000.,
            MBps: (MBps*100.).round()/100.,
            shrink: (shrink*1000.).round()/1000.
        }
    }
}

pub fn compress_the_target(cs: &str, ct: &str) -> CompressionResult {
    use std::*;
    use std::io::Write;
    let source_p = path::Path::new(cs);
    let target_p = path::Path::new(ct);
    if target_p.exists() { fs::remove_file(target_p); }
    let data = fs::read(source_p).unwrap();
    let t0 = time::Instant::now();
    {
        let target = fs::File::create(target_p).unwrap();
        let buffer = io::BufWriter::with_capacity(65536, target);
        let mut zw = zip::ZipWriter::new(buffer);
        zw.start_file(
            source_p.file_name().unwrap().to_str().unwrap(),
            zip::write::FileOptions::default().compression_method(
                zip::CompressionMethod::Deflated
            )
        );
        zw.write(data.as_ref());
        zw.finish();
    }
    let elapsed = {
        let d = t0.elapsed();
        (d.as_secs() as f64) + (d.subsec_nanos() as f64)/1e9
    };
    let old_size = fs::metadata(source_p).unwrap().len();
    let new_size = fs::metadata(target_p).unwrap().len();
    
    CompressionResult::from(elapsed, old_size, new_size)
}

fn main() {
    let compression_source = "speed.log";
    let compression_target = "speed-rust.zip";
    println!("{:?}", compress_the_target(compression_source, compression_target));
}
```

You can get the same report for the command-line version by calling it as an external process, e.g. here in Python:

```python
import time
import subprocess
import os

cmdline_compression_source = 'speed.log'
cmdline_compression_target = 'speed-cmdline.zip'

def compress_the_target():
    if os.path.isfile(cmdline_compression_target):
        os.remove(cmdline_compression_target)
    t0 = time.time()
    subprocess.run(['zip', '-7', cmdline_compression_target, cmdline_compression_source])
    elapsed = time.time() - t0
    log_size = os.stat(cmdline_compression_source).st_size
    zip_size = os.stat(cmdline_compression_target).st_size
    rate = (log_size/(1024*1024.0))/elapsed
    factor = zip_size/log_size
    os.remove(cmdline_compression_target)
    return (round(elapsed*1000)/1000, round(rate*100)/100, round(factor*1000)/1000)

compress_the_target()
```

**Comment by xmclark** [comment]
I can look into this more and reproduce the benchmarks.

**Comment by xmclark** [comment]
I recreated the python script and the rust example in an ubuntu VM I made on GCP. I ran a couple test cases and average some of the results. I build the rust app in release mode. zip=0.5.0.

| speed.log | python script                         | rust with zip                          |
|-----------|---------------------------------------|----------------------------------------|
| 1 GB      | dt: 7.981, MBps: 128.3, shrink: 0.001 | dt: 8.883, MBps: 115.28, shrink: 0.001 |
| 1 MB      | dt: 0.01, MBps: 97.05, shrink: 0.001  | dt: 0.01, MBps: 97.19, shrink: 0.001   |

The results seems to suggest that deflate is going to run a little slower for large files, and that is probably a deficiency of the chosen implementation.

This crate at one point was using the `flate2` which uses the libc implementation of deflate, as far as I know. It is no surprise that the builds have gotten bigger after it switch to use `libflate`. @mvdnes and I talked about keeping both as optional dependencies, but decided having only one implementation was better.

**Comment by xmclark** [comment]
The first experiment I tried was with a generated file using the `dd` command. I think it was mostly empty, so I thought that may have had an effect on the shrink. 

I tried again by getting a random json file. I used one that was 13 MB. I ran the tests and got similar results.

This is the file I used:
[speed.log](https://github.com/mvdnes/zip-rs/files/2647746/speed.log)

| speed.log | python script                         | rust with zip                        |
|-----------|---------------------------------------|--------------------------------------|
| 13 MB     | dt: 0.541, MBps: 24.31, shrink: 0.231 | dt: 0.575, MBps: 22.91, shrink: 0.29 |

@Ichoran can you try reproducing the test with that file? Or give me another file to help me reproduce?

**Comment by Ichoran** [comment]
That's what I get too, roughly, but do you notice how much better the Python shrink is that the Rust shrink?  The two are comparable in speed, but not at all in size.

It's easiest to measure the speed with the `zip` command-line utility rather than the Python script (for short times like this the startup is also probably less; in the past I've tested and it's close to identical).  Here if I run

```
for i in `seq 1 9`; do
  /usr/bin/time -f "%E real" zip -q -$i $i.zip speed.log;
done
```

on my machine, I get the following times corresponding to increasing compression levels:

```
0:00.17 real
0:00.13 real
0:00.15 real
0:00.18 real
0:00.23 real
0:00.26 real
0:00.29 real
0:00.52 real
0:00.61 real
```

And this produced the corresponding file sizes:

```
~/temp/zipspeed$ ls  -sk1
total 57000
 3780 1.zip
 3576 2.zip
 3440 3.zip
 3380 4.zip
 3232 5.zip
 3136 6.zip
 3120 7.zip
 3084 8.zip
 3080 9.zip
13484 speed.log
```

Now if we try the Rust code we get

```
~/temp/zipspeed$ /usr/bin/time -f "%E real" rzst/target/release/rzst
CompressionResult { dt: 0.34, MBps: 38.73, shrink: 0.29 }
0:00.34 real
```

And the file size is

```
 3916 speed-rust.zip
```

So we see that the compression is worse than the very lowest level offered by the command-line utility (`-1`) and is 2x slower than that one.  At the same speed (Python script, or zip -7 roughly), Rust is achieving around 4M sizes while zip is barely more than 3M.

So what you're seeing is correct: the issue is that zip-rs is using minimal compression, which ought to be fast but actually isn't.

So there are two problems:

1. At the compression level we get by default, Rust ought to be way faster, and
2. We ought to be able to get better compression from Rust

**Comment by tytouf** [comment]
Hi, what's the status ? Are all possible improvements in performance in libflate or is there some low hanging fruits in zip-rs as well ?

**Comment by JockeTF** [comment]
I've been playing around with Rust for a bit and noticed this as well.

I was trying to read a large text file line by line and immediately noticed the performance issues.

```rust
use std::fs::File;  
use std::io::{BufRead, BufReader};  
use std::time::Instant;                                               
use zip::read::{ZipArchive, ZipFile};  
  
fn count(reader: BufReader<ZipFile>) -> usize {  
    let mut counter: usize = 0;  
      
    for line in reader.lines() {  
        counter += line.unwrap().len();  
    }  
       
    counter  
}                  
   
fn main() {  
    let file = File::open("sample.zip").unwrap();  
                                                       
    let mut archive = ZipArchive::new(file).unwrap();    
    let index = archive.by_name("index.json").unwrap();       
    let reader = BufReader::with_capacity(8_000_000, index);
                               
    let now = Instant::now();   
    let chars = count(reader);               
    let duration = now.elapsed().as_secs();
                                                                      
    println!("Counted {} characters in {} seconds.", chars, duration);
}
```

```shell
$ cargo run --release
Counted 841837181 characters in 105 seconds.
```

```python
#!/usr/local/bin python3

from io import BufferedReader
from time import time
from zipfile import ZipFile

def count(reader: BufferedReader) -> int:
    counter = 0
    
    for line in reader:
        counter += len(line)
                   
    return counter

def main() -> None:
    with ZipFile('sample.zip') as zobj:   
        with zobj.open('index.json') as fobj:
            reader = BufferedReader(fobj, 8_000_000)  # type: ignore
    
            start = time()
            chars = count(reader)
            diff = time() - start

    print(f"Counted {chars} characters in {diff:.02f} seconds.")

if __name__ == '__main__':
    main()
```

```shell
$ python3 counter.py
Counted 842011682 characters in 3.10 seconds.
```

I'm very new to Rust though, so perhaps I'm doing something wrong?

You can try it yourself with [the same code and data](http://jocketf.se/p/JyYSpLdFWY5E9QtB1nwyaj/counter.zip) (150 MB).

**Comment by quininer** [comment]
The code quality of `libflate` [is](https://github.com/sile/libflate/issues/16) [not](https://github.com/sile/libflate/issues/21) [ideal](https://github.com/sile/libflate/issues/22), and `flate2` has implemented [wasm support](https://github.com/alexcrichton/flate2-rs/issues/161#issuecomment-439611598). Maybe switching back `flate2` would be a good option.
