### ISSUE TITLE
ZipFile reader returns less bytes than file contains.

### ISSUE THREAD

**Issue by john-terrell** [mvdnes/zip-rs#92]
Hi, I'm using this crate to parse zip files containing binary logs.  Using 0.5.0, parsing the files using a reader from ZipFile returns the file contents up until about 1/4 of the way through the file when it returns a truncated read.   I verified my code works correctly on a non-zipped file.   I also tried using v0.4.2 and it failed even sooner on the same input.   Enclosed is a sample zip file.

[Archive.zip](https://github.com/mvdnes/zip-rs/files/2716883/Archive.zip)

Let me know how I can help narrow this down.

**Comment by john-terrell** [comment]
Follow-up info:  
OS: OSX 10.14.2
rustc 1.31.0 (abe02cefd 2018-12-04)

**Comment by john-terrell** [comment]
Verified same behaviour running Linux.

**Comment by john-terrell** [comment]
Here's a sample project that demonstrates the issue.   
[ziptest.zip](https://github.com/mvdnes/zip-rs/files/2716976/ziptest.zip)

**Comment by john-terrell** [comment]
For the previous code, it's possible I'm misunderstanding how the reader should work.   I stop reading when the reader returns fewer bytes read than I asked for.   :-)    When I change the buffer size to a single byte, it appears to read all the way through.

**Comment by mvdnes** [comment]
You probably wanted to use the function [read_exact]. This method retries reading until the entire buffer is filled.

[read_exact]: https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact

**Comment by john-terrell** [comment]
Of course!    Thanks for setting me straight!
